# UDP multicast - 224.1.1.1:5007
# Run: docker compose up

services:
  multicast_receiver1:
    build:
      context: .
      dockerfile: Dockerfile.multicast_receiver
    command: ["--duration", "15"]
    networks:
      - multicast

  multicast_receiver2:
    build:
      context: .
      dockerfile: Dockerfile.multicast_receiver
    command: ["--duration", "15"]
    networks:
      - multicast

  multicast_sender1:
    build:
      context: .
      dockerfile: Dockerfile.multicast_sender
    depends_on:
      - multicast_receiver1
    environment:
      - SENSOR_TYPE=temp
    networks:
      - multicast

  multicast_sender2:
    build:
      context: .
      dockerfile: Dockerfile.multicast_sender
    depends_on:
      - multicast_receiver1
    environment:
      - SENSOR_TYPE=humidity
    networks:
      - multicast

networks:
  multicast:
